---
app_user: django
app_group: django
app_dir: /opt/django-app
venv_dir: "{{ app_dir }}/venv"
app_service_name: django-app
app_bind_host: 127.0.0.1
app_bind_port: 8000


allowed_hosts: "{{ alb_dns_name }}"
site_root: "http://{{ alb_dns_name }}"


db_host: "{{ db_private_ip }}"
db_name: "{{ postgres_db }}"
db_user: "{{ postgres_user }}"
db_password: "{{ postgres_password }}"
db_port: "{{ postgres_port }}"
