---
- name: Install web server base packages
  ansible.builtin.dnf:
    name: "{{ webserver_packages }}"
    state: present

- name: Create application group
  ansible.builtin.group:
    name: "{{ app_group }}"
    state: present

- name: Create application system user
  ansible.builtin.user:
    name: "{{ app_user }}"
    group: "{{ app_group }}"
    system: true
    create_home: true
    home: "{{ app_dir }}"
    shell: /sbin/nologin
    state: present

- name: Create application directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0755"
