---
- name: Install packages
  ansible.builtin.import_tasks: packages.yml


- name: Generate env file
  ansible.builtin.import_tasks: envs.yml


- name: Run migrations
  ansible.builtin.import_tasks: migration.yml


- name: Start application service
  ansible.builtin.import_tasks: run-server.yml
