---
- name: Gather facts from application servers
  hosts: webservers
  gather_facts: true

- name: Configure PostgreSQL server
  hosts: db
  become: true
  gather_facts: true
  roles:
    - postgres-setup
