---
- name: Restart app service
  ansible.builtin.systemd_service:
    name: "{{ app_service_name }}"
    state: restarted

- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
